name: Pipeline de Integracion Continua DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Validacion de Entorno y Codigo
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Simular Verificacion
      run: |
        echo "Iniciando pipeline de DevOps en repositorio Mendez..."
        echo "Entorno validado con exito. ¡Todo limpio!"